# Generated by Django 4.1 on 2022-08-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names_gender_api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='names_gender',
            name='gender',
            field=models.CharField(choices=[('unknown', 'unknown'), ('male', 'Male'), ('female', 'Female')], default='unknown', max_length=256),
        ),
    ]
